vergecurrency/vergecurrency.com

- _includes/head.html
> fix css loading

- index.html
@vergecurrency 
- Updates the Verge homepage description text
> Update homepage description text

- _sass/cloud-animation.scss
- _sass/main.scss
- index.html
- Creates a subtle transparent cloud animation to make the homepage feel more dynamic
**Note:** The animated GIF doesn't render it very well (it's not janky)
> Create subtle cloud animation

- _sass/cloud-animation.scss
- _sass/main.scss
- Turns off the cloud animation for devices **<500px** (it's not as smooth on mobile devices)
- Updates the cloud colors/speed
> Cloud Animation Cleanup

- _sass/cloud-animation.scss
- _sass/main.scss
- index.html
- Make sure all text is clickable if the cloud is over it
- Makes the clouds more realistic
> More cloud cleanup

- FAQ/index.html
Just a few questions to add if dev approves. Will add more as I think of them.
> Update FAQ index.html

- _sass/wallet-download-buttons.scss
> Small margin fix

- .gitignore
- README.md
> Updated .gitigore and Added TODO

- _includes/head.html
- _plugins/cachebuster.rb
@vergecurrency @CryptoRekt @hellokarma
- Adds a cache busting plugin for the CSS (to make sure users see updated styles at all times)
> Add cache busting for the site CSS

- _includes/home/footer.html
Update Verge Radio URL to http://radiocrypto.com
> Update Verge Radio URL

- _data/langs/es.yml
- _data/langs/nl.yml
- _data/langs/pt.yml
Three lang files has been modified:
1. NL
2. PT (Thanks Barba Negra)
3. ES (Thanks rathleon)
> Added three translations for the developers home

- _data/langs/es.yml
added august roadmap translated
> roadmap translation

- README.md
@vergecurrency @CryptoRekt @hellokarma 
- Updates the README contributing section
> Updated Contributing Section of README - Other Updates Will Come Later

- README.md
- _config.yml
- _data/langs/en.yml
- _includes/home.html
- _includes/home/donate.html
- _includes/shared/header.html
- _sass/donate.scss
- _sass/main.scss
@vergecurrency @CryptoRekt @hellokarma
- Adds a new **Donate** section to the homepage (lists XVG and Bitcoin wallet addresses)
- Adds a new `basePath` page variable that can be used to easily create relative links
- Updates the english language path in the dropdown to point back at the homepage instead of a lang specific folder
> Add Donate Section

- _data/langs/en.yml
- _includes/home/wallets.html
- Adds an info alert about downloading the Verge blockchain from vergecurrency.de in the **wallets** section
> Add vergecurrency.de Info Alert 

- _data/langs/it.yml
Hey guys! Now it's Puuuuurfect, and it sounds really italian!
If u feel like donting me some xvg I'd be SUPA happy
DH3Cji1DHkLtpqMt95T1UzBcrNNxiR56ou
> In Mafia language

- _data/langs/ja.yml
Updates the Japanese translation for the main site. Could use refinement from a native speaker, but an improvement on the current translation.
> Updated Japanese Translation

- _data/langs/en.yml
- _includes/home.html
- _includes/home/splash.html
- _includes/home/wallets.html
- _includes/shared/notificationbar.html
- _sass/main.scss
- _sass/notificationbar.scss
- Adds a notification bar to the top of the homepage for the new Android TOR wallet
> Add a notification bar component for the Android TOR release

- _data/langs/fr.yml
Updating the french translation of the website : VergeCurrency.com
date : 01/08/2017
2Dai
> Update of french version of the website

- _data/langs/en.yml
- _includes/faq.html
- _includes/home/info.html
- _includes/shared/footer.html
- _includes/shared/header.html
- _sass/header.scss
- _sass/info.scss
- _sass/main.scss
- Updates the **About** section to include cards from our marketing infographic (icons are being used from Font Awesome)
- Fixes the desktop sticky header so that the page doesn't jump and it does a nice fade in CSS transition
- Fixes the FAQ individual URL's to strip the question mark (since Slack, Twitter, and other sites strip it... making it more difficult to share)
- Adds the Verge block explorer to the resources section
> Update About Section, Tweak Desktop Sticky Header, Update FAQ urls

- _data/langs/ko.yml
> Add Korean Translated FAQ

- README.md
People don't understand how exchange addresses work. Changing this to a private wallet.
> Changing wallet addresses.

- _data/langs/ru.yml
- _includes/home/wallets.html
1. Link to the new Windows Electrum wallet updated
2. Minor fix in the Russian version
> Windows Electrum link + fixes

- _data/langs/ko.yml
- _data/langs/zh_CN.yml
1. Chinese content
2. Chinese FAQ
3. Mino fixes of typos in Korean
> Chinese Website + fixes

- _data/langs/en.yml
- _includes/home/roadmap.html
- _sass/buttons.scss
- _sass/exchanges.scss
- _sass/header.scss
- _sass/info.scss
- _sass/main.scss
I made a few tweaks to make things sit a bit better and, I think, look nicer (more professional). Also made the capitalization of Tor, I2C, and Verge consistent. And some other minor English text changes. Nothing major, but I think it improves the overall image.
http://i.imgur.com/4M9s248.jpg
http://i.imgur.com/vUdAEWu.png
> Layout and style improvements

- pools/index.html
> Add Multipool.us to pools

- pools/index.html
> Add UniMining.net to pools (blake2s)

- _includes/shared/footer.html
Fixed the email address link that was malformed, causing a 404 response code (a broken page). This was causing 47 broken pages.
> Updated email address

- paper-wallet/index.html
Changed (.RAR file) to (.ZIP file) and changed url to direct download
> Change download link in paper wallet

- mining/index.html
- paper-wallet/index.html
I started and issue regarding the problems direct download links and security warnings. I've updated the mining list. After this is posted then site reviews can be requested.
> Updates to mining index.html

- _data/langs/en.yml
new domain to download the blockchain zip from: https://verge-blockchain.com
> switch domain blockchain zip file

- _data/langs/de.yml
Added some missing translations in german
> Translations added

- _data/langs/de.yml
I'm sorry for doing it wrong first time :)
> Translation correction

- _data/langs/de.yml
- _data/langs/en.yml
- _includes/shared/header.html
- _includes/shared/stickyheader.html
updated german language file and changed some links as setting https://domain.org/#donate
is a bad idea, especially if using /lang/de
> translation and link issues

- .gitignore
- CNAME
- _data/langs/de.yml
- _data/langs/en.yml
- _includes/home/info.html
- _includes/home/roadmap.html
- _includes/home/vendors.html
- _includes/p2p.html
- _includes/shared/footer.html
- _includes/shared/header.html
- _includes/shared/stickyheader.html
- langs/ar/p2p.html
- langs/da/p2p.html
- langs/de/p2p.html
- langs/en/p2p.html
- langs/es/p2p.html
- langs/fr/p2p.html
- langs/it/p2p.html
- langs/ja/p2p.html
- langs/ko/p2p.html
- langs/nl/p2p.html
- langs/pl/p2p.html
- langs/pt/p2p.html
- langs/ro/p2p.html
- langs/ru/p2p.html
- langs/zh_CN/p2p.html
- langs/zh_TW/p2p.html
- radio/fonts/flaticon-liveradio/flaticon.css
- radio/index.html
- sitemap.xml
- fixed some links / paths
- roadmap
- and added p2p language configuration for translation availability
> p2p lang + roadmap update + some minor improvements

- _includes/home/roadmap.html
After release of the new Verge Wallet, we've to update the roadmap
> Updated Roadmap

- _data/langs/da.yml
- _data/langs/de.yml
- _data/langs/es.yml
- _data/langs/fr.yml
- _data/langs/it.yml
- _data/langs/nl.yml
- _data/langs/pl.yml
- _data/langs/pt.yml
- _data/langs/ro.yml
- _data/langs/ru.yml
- _includes/shared/header.html
- _includes/shared/stickyheader.html
fixing header+stickyheader links @CryptoRekt hope thats fine now for you. Personally for me it works fine locally
added some missing **strong** attributes to the multilanguage tagline
> fix header links  + tagline

- pools/index.html
Removing the https:// for multipool.sonofatech.com to make it http://multipool.sonofatech.com
> Updating Pools Page for Sonofatech

- Gemfile.lock
- _data/langs/de.yml
- _data/langs/en.yml
- _data/langs/es.yml
- _includes/mining.html
- mining/index.html
// created "new" mining site
-> which is integrated within current design (with header/footer)
> fixing "es" lang

- _data/langs/en.yml
let me know if this is the correct one and I can update the other Langs
> verge team address to tip the Verge Team

- _data/langs/nl.yml
Translated in a word processor so quotation marks were off in the last commit, fixed now.
> Fixed mistakes

- _includes/home/vendors.html
resolved broken URL for Trebaltek.ca
> Fixed broken vendor URL

- _data/langs/en.yml
- _sass/vendors.scss
Made changes to the text size and image position to fix alignment issues on vendors segment.
> Vendor text changes

- _data/langs/ar.yml
- _data/langs/da.yml
- _data/langs/de.yml
- _data/langs/en.yml
- _data/langs/es.yml
- _data/langs/fr.yml
- _data/langs/it.yml
- _data/langs/ja.yml
- _data/langs/ko.yml
- _data/langs/nl.yml
- _data/langs/pl.yml
- _data/langs/pt.yml
- _data/langs/ro.yml
- _data/langs/ru.yml
- _data/langs/zh_CN.yml
- _data/langs/zh_TW.yml
This is going to be a great year!
> Welcome in 2018 :-)

- _includes/security.md
- security/rfc2350.md
This is the charter for Verge-CSIRT.
Todo: 
-Create /security landing page for Verge Security Team
-Create security@vergecurrency.com email
> Verge-CSIRT

- pools/index.html
> Add Suprnova

- Gemfile.lock
- _data/langs/it.yml
improvement + additions to Italian translation.
> Updates to it.yml

- _sass/wallet-tabs.scss
Fixed the wallet tabs, so that they display better on mobile devices.
> Fixed the wallet tabs on mobile

- _sass/main.scss
Added `15px` padding to the sides of the sections for a better mobile experience.
> Fixed small padding issue on mobile devices

- _data/langs/en.yml
- _data/langs/es.yml
- _data/langs/fr.yml
- _data/langs/ko.yml
- _data/langs/nl.yml
- _data/langs/pt.yml
- _data/langs/ru.yml
- _data/langs/zh_CN.yml
https://github.com/vergecurrency/vergecurrency.com/issues/275
> update richlist link

- _includes/home/vendors.html
> Change vendor name to the rightone

- _data/langs/fr.json
Corrected common errors "dévelopeur" to "développeur" and similars
Corrected some syntax errors
Translated a bunch of questions
> Added translations to fr.json

- pools/index.html
Added new list item for x17 Algo CarpeCrypto Verge Pool at http://verge.carpecrypto.me
> Add CarpeCrypto Verge Pool

- pages/community/xvg-mining-pools.js
adding hashfaster.com pool to website
> adding hashfaster.com

- pages/community/xvg-mining-pools.js
Added Lyra2Rev2 to Poolovich.PRO pool
> Added Lyra2Rev2 to Poolovich.PRO pool

- pages/community/xvg-mining-pools.js
> Please update and include NLpool.nl for X17

- pages/wallets.js
Change "public And private ledgers" to "public and private ledgers".
> Fix one punctuation error on wallets.js

- components/Medium.js
- static/scss/global.scss
- static/scss/partials/_mentions.scss
Hotfix for image breaking outside container by creating a new stylesheet partial intended for mentions
> Pressrelease Medium Image style error

- locales/en/team.json
> Added my Twitter and Github account

- locales/en/team.json
> team addition

- locales/en/home.json
- locales/en/wallets.json
> Update 1 bad instructions link and homepage grammar minor fix

- components/Sponsors.js
- locales/en/sponsors.json
> Remove Hyatt logo

- pages/index.js
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.
> Update index.js roadmap section to sync with new /roadmap updates yesterday

- locales/en/team.json
> Updating GreenAzn information about his occupation at verge

- locales/en/exchanges.json
> Update exchanges.json - cryptomate has XVG disabled

- locales/en/home.json
- pages/key-tech.js
> update wraith protocol

- locales/en/exchanges.json
- static/img/exchanges/indacoin.svg
> Adding Indacoin as exchnage option

- pages/presskit.js
> tweaks on presskit page

- locales/en/faq.json
- locales/en/home.json
- pages/benefits.js
- pages/business.js
- pages/key-tech.js
- pages/presskit.js
> update WP descriptions across all pages

- locales/en/team.json
> Update cryptogirls twitter handle

- pages/community/xvg-mining-pools.js
Added Blockmasters.co url to the applicable algos
- [X ] I have read the **CONTRIBUTING** document.
- [X ] My code follows the code style of this project.
> Blockmasters.co to Scrypt, Lyra2Rev2 & X17 on mining pages

- components/MenuItems.js
- [] My change requires a change to the documentation.
> Feature find us menu

- pages/roadmap.js
> Spelling mistake (roadmap)

- components/MenuItems.js
- pages/CurrentYearRoadmap.js
- pages/index.js
- pages/roadmap.js
> Unifying Roadmap structure on Homepage and Roadmap

- pages/CurrentYearRoadmap.js
> Fixing spelling

- locales/en/vendors.json
> Update first 12 vendor order

- pages/partnership-donation-rewards.js
Added the donators names.
Turn off the bottom link
> Added the donators names

- pages/community/xvg-mining-pools.js
> added BSOD.PW blake2s

- locales/en/team.json
> Updated Team page

- lists/wallets.json
Updated GitHub Wiki to modify installation instructions, changed link from medium article to GitHub Wiki Location
> Updated MacOS link to github location

- locales/en/benefits.json
- pages/benefits.js
> benefits page - updated for translations

- lists/vendors.json
website unavailable -- searched and didn't see any new website / etc
> Update vendors.json - remove falmouth boat security

- pages/community/xvg-mining-pools.js
Also fixed BSOD.PW URLs to link directly to algo page
> Added BSOD Pool to all Verge algos

- lists/team.json
- [X ] All new and existing tests passed.
> Updated the Team page

- static/scss/partials/_wallets.scss
> fix paper wallet icon

- lists/vendors.json
> New Vendor LawOfficesJasonD

- lists/wallets.json
OSX Tor link changed to Zendesk Article
Windows Tor Link Changed to Zendesk Article
Windows tor Electrum Wallet changed to Zendesk Article
> Update to Help Locations

- components/TGAdmins.js
- lists/team.json
- lists/tgadmins.json
- pages/verge-team.js
> add telegram admins to team page

- pages/CurrentYearRoadmap.js
Yup no explanation needed on this 🤓
> Update iOS progress to 25%

- components/LanguageSwitcher.js
- components/TeamCategory.js
- components/Wallets.js
- components/WalletsBtn.js
- locales/updateLanguages.js
- pages/index.js
- pages/key-tech.js
- pages/wallets.js
- static/scss/pages/_home.scss
- static/scss/pages/_key-tech.scss
- static/scss/pages/_team.scss
- static/scss/partials/_benefits.scss
- static/scss/partials/_wallets.scss
no comment provided? Well just copied #536 and fixed some stuff. :)
> RTL V3 - Support Right to left languages.

- lists/vendors.json
> New Vendor_Mobisun.com

- components/LanguageSwitcher.js
- lists/team.json
> Added Team members CryptoT, cloakfox, Jimbobaroobob

- static/scss/partials/_partners.scss
Let's all avoid that @SwenVanZanten  opens other issues
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
- [x ] My code follows the code style of this project.
> Fix gray gradient on Safari

- pages/CurrentYearRoadmap.js
> Update iOS progress to 30%

- pages/CurrentYearRoadmap.js
> Update iOS to 35%

- lists/exchanges.json
- lists/vendors.json
> Updated Exchanges/Vendor list

- pages/CurrentYearRoadmap.js
> iOS progress to 40%

- package.json
> Compatibility

- next.config.js
- [x ] Bug fix (non-breaking change which fixes an issue)
> fix for next.config

- pages/fbv.js
> fix for fbv root paths

- static/scss/partials/_base.scss
- [x ] Bug fix (non-breaking change which fixes an issue)
> find-us-fix

- pages/fueled-by-verge.js
- [x ] New feature (non-breaking change which adds functionality)
> change fbv join the movement areas to link to google doc per request

- lists/vendors.json
> small fix on Mobisun.com

- pages/roadmap.js
As we are no longer basing things by quarter at this time.
> Remove years from roadmap

- pages/roadmap.js
> Fix Typo locally

- lists/team.json
- [ x] Bug fix (non-breaking change which fixes an issue)
> Update Kris twitter handle

- lists/vendors.json
vendor website deleted/ unavailable
> remove vendor

- pages/CurrentYearRoadmap.js
> Update iOS status to beta development

- lists/team.json
> CyptoT Twitter update

- lists/exchanges.json
> Remove duplicated Exchange

- pages/community/xvg-mining-pools.js
> Update mining pool website

- pages/community/xvg-mining-pools.js
Added X17 and Multialgo ( Hash to Verge)
> Added Mining-Dutch algo's and MultiHashing

- pages/get-started.js
> spelling on get-started

- pages/CurrentYearRoadmap.js
> Update iOS progress to 60% 👩‍🔬

- lists/sponsors-2019.json
> CryptoCulture sponsor to dolphin sponsor

- pages/CurrentYearRoadmap.js
> Update iOS progress

- pages/meetup.js
This reverts commit c0bd963ac9305d5db470e5c0387b34b769677ffc.
> Revert "Meetup - March 1 Updates (#644)"

- lists/exchanges.json
> Move Bitladon up the exchange list

- pages/meetup.js
> Remove vip deck entrance

- components/Exchanges.js
- components/Vendors.js
> update numbers of static

- pages/index.js
> Cleaned up index

- pages/CurrentYearRoadmap.js
> Minor modification

- static/scss/pages/_team.scss
> iOS filter css glitch fix

- next.config.js
- pages/wallets/terms.js
- static/wallets/terms/index.html
Adding a terms of use and privacy policy page to the website.
This is needed for the App Store
> Add a wallets terms and privacy policy page

- lists/wallets.json
- pages/CurrentYearRoadmap.js
> Fix typo and wrong class assignment

- components/Sponsors-2019.js
- pages/meetup.js
> Meetup Tweaks

- pages/meetup.js
Meetup schedule changed to final
> Change meetup schedule

- components/MenuItems.js
> Update MenuItems.js to hide meetup menu

- lists/vendors.json
> Vendor link change

- pages/get-verge.js
- static/scss/pages/_get-verge.scss
> Widget tweaks

- lists/exchanges.json
* having a volume >= 0.01 BTC
* valid & approved HTTPS certificate
* website reachable
* support long-term Verge trades/buy/sell options
> Remove certain exchanges that didn't meet following criteria

- pages/community/xvg-mining-pools.js
> Add mining pool

- locales/en/faq.json
- [] Bug fix (non-breaking change which fixes an issue)
npm run add-contributor amandamarquis1
> Fix spelling of "source" on website

- lists/team.json
- [ X] I have read the **CONTRIBUTING** document.
- [ X] My code follows the code style of this project.
- [X ] All new and existing tests passed.
> Removed Jeroen and myself from the team page

- lists/vendors.json
> Add Vendor_Nomad Postbox

- lists/vendors.json
> Add new Vendor

- locales/en/common.json
> fix typo on en homepage

- pages/index.js
> Update Youtube Link

- lists/exchanges.json
- pages/CurrentMilestones.js
> Update exchanges list

- components/Partners.js
- lists/team.json
- lists/tgadmins.json
> Team / Partner text updates

- static/version
enabling the update check functionality of the new Electrum Client
> valid signature Electrum v4.0.1

- components/Partners.js
- lists/vendors.json
> General updates

- lists/wallets.json
- pages/index.js
- static/scss/partials/_header.scss
> Text updates / css tweaks

- pages/community/get-involved.js
> Updates verge ambassador text

- components/Team.js
- lists/team.json
> add twitter alter option in team

- lists/team.json
- pages/verge-team.js
> Team page add Executive Team section

- lists/team.json
> miheal twitter and occupation change

- lists/exchanges.json
> adds Binance Connect to get-verge page

- lists/exchanges.json
> Updates Binance Connect to filter XVG on load

- components/Exchanges.js
> add time stamp in binancecnt exchange url

- lists/team.json
> Remove Numan from Team page

- lists/team.json
-  I have read the **CONTRIBUTING** document.
-  My code follows the code style of this project.
> removes titles from teams page

- package.json
- yarn.lock
Reverts vergecurrency/vergecurrency.com#1139
> Revert "Bump next from 4.2.3 to 14.1.1"
